from enum import Enum


class AllureTag(str, Enum):
    COURSES = "COURSES"
    REGRESSION = "REGRESSION"
    DASHBOARD = "DASHBOARD"
    REGISTRATION = "REGISTRATION"
    NAVIGATION = "NAVIGATION"
    AUTHORIZATION = "AUTHORIZATION"
